// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/aikowocki/yandex-go-final-diploma/internal/server/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockVaultRepository is an autogenerated mock type for the VaultRepository type
type MockVaultRepository struct {
	mock.Mock
}

type MockVaultRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVaultRepository) EXPECT() *MockVaultRepository_Expecter {
	return &MockVaultRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, v
func (_m *MockVaultRepository) Create(ctx context.Context, v domain.Vault) (domain.Vault, error) {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Vault
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Vault) (domain.Vault, error)); ok {
		return rf(ctx, v)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Vault) domain.Vault); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Get(0).(domain.Vault)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Vault) error); ok {
		r1 = rf(ctx, v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVaultRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVaultRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - v domain.Vault
func (_e *MockVaultRepository_Expecter) Create(ctx interface{}, v interface{}) *MockVaultRepository_Create_Call {
	return &MockVaultRepository_Create_Call{Call: _e.mock.On("Create", ctx, v)}
}

func (_c *MockVaultRepository_Create_Call) Run(run func(ctx context.Context, v domain.Vault)) *MockVaultRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Vault))
	})
	return _c
}

func (_c *MockVaultRepository_Create_Call) Return(_a0 domain.Vault, _a1 error) *MockVaultRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVaultRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Vault) (domain.Vault, error)) *MockVaultRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockVaultRepository) ListByUser(ctx context.Context, userID string) ([]domain.Vault, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []domain.Vault
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Vault, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Vault); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Vault)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVaultRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockVaultRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockVaultRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockVaultRepository_ListByUser_Call {
	return &MockVaultRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockVaultRepository_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockVaultRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVaultRepository_ListByUser_Call) Return(_a0 []domain.Vault, _a1 error) *MockVaultRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVaultRepository_ListByUser_Call) RunAndReturn(run func(context.Context, string) ([]domain.Vault, error)) *MockVaultRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVaultRepository creates a new instance of MockVaultRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVaultRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVaultRepository {
	mock := &MockVaultRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
