// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/aikowocki/yandex-go-final-diploma/internal/server/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BumpVaultVersion provides a mock function with given fields: ctx, vaultID
func (_m *MockRepository) BumpVaultVersion(ctx context.Context, vaultID string) error {
	ret := _m.Called(ctx, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for BumpVaultVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, vaultID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_BumpVaultVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BumpVaultVersion'
type MockRepository_BumpVaultVersion_Call struct {
	*mock.Call
}

// BumpVaultVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID string
func (_e *MockRepository_Expecter) BumpVaultVersion(ctx interface{}, vaultID interface{}) *MockRepository_BumpVaultVersion_Call {
	return &MockRepository_BumpVaultVersion_Call{Call: _e.mock.On("BumpVaultVersion", ctx, vaultID)}
}

func (_c *MockRepository_BumpVaultVersion_Call) Run(run func(ctx context.Context, vaultID string)) *MockRepository_BumpVaultVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_BumpVaultVersion_Call) Return(_a0 error) *MockRepository_BumpVaultVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_BumpVaultVersion_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_BumpVaultVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, s
func (_m *MockRepository) Create(ctx context.Context, s domain.Secret) (domain.Secret, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Secret) (domain.Secret, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Secret) domain.Secret); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Get(0).(domain.Secret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Secret) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s domain.Secret
func (_e *MockRepository_Expecter) Create(ctx interface{}, s interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, s domain.Secret)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Secret))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 domain.Secret, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Secret) (domain.Secret, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetForUpdate provides a mock function with given fields: ctx, secretID, userID
func (_m *MockRepository) GetForUpdate(ctx context.Context, secretID string, userID string) (domain.Secret, error) {
	ret := _m.Called(ctx, secretID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetForUpdate")
	}

	var r0 domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Secret, error)); ok {
		return rf(ctx, secretID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Secret); ok {
		r0 = rf(ctx, secretID, userID)
	} else {
		r0 = ret.Get(0).(domain.Secret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, secretID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForUpdate'
type MockRepository_GetForUpdate_Call struct {
	*mock.Call
}

// GetForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
//   - userID string
func (_e *MockRepository_Expecter) GetForUpdate(ctx interface{}, secretID interface{}, userID interface{}) *MockRepository_GetForUpdate_Call {
	return &MockRepository_GetForUpdate_Call{Call: _e.mock.On("GetForUpdate", ctx, secretID, userID)}
}

func (_c *MockRepository_GetForUpdate_Call) Run(run func(ctx context.Context, secretID string, userID string)) *MockRepository_GetForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetForUpdate_Call) Return(_a0 domain.Secret, _a1 error) *MockRepository_GetForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetForUpdate_Call) RunAndReturn(run func(context.Context, string, string) (domain.Secret, error)) *MockRepository_GetForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetPayload provides a mock function with given fields: ctx, secretID, userID
func (_m *MockRepository) GetPayload(ctx context.Context, secretID string, userID string) (domain.Secret, error) {
	ret := _m.Called(ctx, secretID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPayload")
	}

	var r0 domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Secret, error)); ok {
		return rf(ctx, secretID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Secret); ok {
		r0 = rf(ctx, secretID, userID)
	} else {
		r0 = ret.Get(0).(domain.Secret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, secretID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayload'
type MockRepository_GetPayload_Call struct {
	*mock.Call
}

// GetPayload is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
//   - userID string
func (_e *MockRepository_Expecter) GetPayload(ctx interface{}, secretID interface{}, userID interface{}) *MockRepository_GetPayload_Call {
	return &MockRepository_GetPayload_Call{Call: _e.mock.On("GetPayload", ctx, secretID, userID)}
}

func (_c *MockRepository_GetPayload_Call) Run(run func(ctx context.Context, secretID string, userID string)) *MockRepository_GetPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetPayload_Call) Return(_a0 domain.Secret, _a1 error) *MockRepository_GetPayload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetPayload_Call) RunAndReturn(run func(context.Context, string, string) (domain.Secret, error)) *MockRepository_GetPayload_Call {
	_c.Call.Return(run)
	return _c
}

// ListIndex provides a mock function with given fields: ctx, vaultID, userID
func (_m *MockRepository) ListIndex(ctx context.Context, vaultID string, userID string) ([]domain.Secret, error) {
	ret := _m.Called(ctx, vaultID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListIndex")
	}

	var r0 []domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Secret, error)); ok {
		return rf(ctx, vaultID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Secret); ok {
		r0 = rf(ctx, vaultID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, vaultID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIndex'
type MockRepository_ListIndex_Call struct {
	*mock.Call
}

// ListIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID string
//   - userID string
func (_e *MockRepository_Expecter) ListIndex(ctx interface{}, vaultID interface{}, userID interface{}) *MockRepository_ListIndex_Call {
	return &MockRepository_ListIndex_Call{Call: _e.mock.On("ListIndex", ctx, vaultID, userID)}
}

func (_c *MockRepository_ListIndex_Call) Run(run func(ctx context.Context, vaultID string, userID string)) *MockRepository_ListIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_ListIndex_Call) Return(_a0 []domain.Secret, _a1 error) *MockRepository_ListIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListIndex_Call) RunAndReturn(run func(context.Context, string, string) ([]domain.Secret, error)) *MockRepository_ListIndex_Call {
	_c.Call.Return(run)
	return _c
}

// ListRow provides a mock function with given fields: ctx, vaultID, userID
func (_m *MockRepository) ListRow(ctx context.Context, vaultID string, userID string) ([]domain.Secret, error) {
	ret := _m.Called(ctx, vaultID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListRow")
	}

	var r0 []domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Secret, error)); ok {
		return rf(ctx, vaultID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Secret); ok {
		r0 = rf(ctx, vaultID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, vaultID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRow'
type MockRepository_ListRow_Call struct {
	*mock.Call
}

// ListRow is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID string
//   - userID string
func (_e *MockRepository_Expecter) ListRow(ctx interface{}, vaultID interface{}, userID interface{}) *MockRepository_ListRow_Call {
	return &MockRepository_ListRow_Call{Call: _e.mock.On("ListRow", ctx, vaultID, userID)}
}

func (_c *MockRepository_ListRow_Call) Run(run func(ctx context.Context, vaultID string, userID string)) *MockRepository_ListRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_ListRow_Call) Return(_a0 []domain.Secret, _a1 error) *MockRepository_ListRow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListRow_Call) RunAndReturn(run func(context.Context, string, string) ([]domain.Secret, error)) *MockRepository_ListRow_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, secretID
func (_m *MockRepository) SoftDelete(ctx context.Context, secretID string) (int64, error) {
	ret := _m.Called(ctx, secretID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, secretID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, secretID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, secretID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
func (_e *MockRepository_Expecter) SoftDelete(ctx interface{}, secretID interface{}) *MockRepository_SoftDelete_Call {
	return &MockRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, secretID)}
}

func (_c *MockRepository_SoftDelete_Call) Run(run func(ctx context.Context, secretID string)) *MockRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_SoftDelete_Call) Return(_a0 int64, _a1 error) *MockRepository_SoftDelete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFields provides a mock function with given fields: ctx, secretID, encRow, encIndex, encPayload
func (_m *MockRepository) UpdateFields(ctx context.Context, secretID string, encRow []byte, encIndex []byte, encPayload []byte) (int64, error) {
	ret := _m.Called(ctx, secretID, encRow, encIndex, encPayload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFields")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, []byte, []byte) (int64, error)); ok {
		return rf(ctx, secretID, encRow, encIndex, encPayload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, []byte, []byte) int64); ok {
		r0 = rf(ctx, secretID, encRow, encIndex, encPayload)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, []byte, []byte) error); ok {
		r1 = rf(ctx, secretID, encRow, encIndex, encPayload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFields'
type MockRepository_UpdateFields_Call struct {
	*mock.Call
}

// UpdateFields is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
//   - encRow []byte
//   - encIndex []byte
//   - encPayload []byte
func (_e *MockRepository_Expecter) UpdateFields(ctx interface{}, secretID interface{}, encRow interface{}, encIndex interface{}, encPayload interface{}) *MockRepository_UpdateFields_Call {
	return &MockRepository_UpdateFields_Call{Call: _e.mock.On("UpdateFields", ctx, secretID, encRow, encIndex, encPayload)}
}

func (_c *MockRepository_UpdateFields_Call) Run(run func(ctx context.Context, secretID string, encRow []byte, encIndex []byte, encPayload []byte)) *MockRepository_UpdateFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].([]byte), args[4].([]byte))
	})
	return _c
}

func (_c *MockRepository_UpdateFields_Call) Return(_a0 int64, _a1 error) *MockRepository_UpdateFields_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateFields_Call) RunAndReturn(run func(context.Context, string, []byte, []byte, []byte) (int64, error)) *MockRepository_UpdateFields_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
