// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/aikowocki/yandex-go-final-diploma/internal/server/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSecretRepository is an autogenerated mock type for the SecretRepository type
type MockSecretRepository struct {
	mock.Mock
}

type MockSecretRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretRepository) EXPECT() *MockSecretRepository_Expecter {
	return &MockSecretRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, s
func (_m *MockSecretRepository) Create(ctx context.Context, s domain.Secret) (domain.Secret, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Secret) (domain.Secret, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Secret) domain.Secret); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Get(0).(domain.Secret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Secret) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSecretRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s domain.Secret
func (_e *MockSecretRepository_Expecter) Create(ctx interface{}, s interface{}) *MockSecretRepository_Create_Call {
	return &MockSecretRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *MockSecretRepository_Create_Call) Run(run func(ctx context.Context, s domain.Secret)) *MockSecretRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Secret))
	})
	return _c
}

func (_c *MockSecretRepository_Create_Call) Return(_a0 domain.Secret, _a1 error) *MockSecretRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Secret) (domain.Secret, error)) *MockSecretRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetPayload provides a mock function with given fields: ctx, secretID, userID
func (_m *MockSecretRepository) GetPayload(ctx context.Context, secretID string, userID string) (domain.Secret, error) {
	ret := _m.Called(ctx, secretID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPayload")
	}

	var r0 domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Secret, error)); ok {
		return rf(ctx, secretID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Secret); ok {
		r0 = rf(ctx, secretID, userID)
	} else {
		r0 = ret.Get(0).(domain.Secret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, secretID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_GetPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayload'
type MockSecretRepository_GetPayload_Call struct {
	*mock.Call
}

// GetPayload is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
//   - userID string
func (_e *MockSecretRepository_Expecter) GetPayload(ctx interface{}, secretID interface{}, userID interface{}) *MockSecretRepository_GetPayload_Call {
	return &MockSecretRepository_GetPayload_Call{Call: _e.mock.On("GetPayload", ctx, secretID, userID)}
}

func (_c *MockSecretRepository_GetPayload_Call) Run(run func(ctx context.Context, secretID string, userID string)) *MockSecretRepository_GetPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSecretRepository_GetPayload_Call) Return(_a0 domain.Secret, _a1 error) *MockSecretRepository_GetPayload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_GetPayload_Call) RunAndReturn(run func(context.Context, string, string) (domain.Secret, error)) *MockSecretRepository_GetPayload_Call {
	_c.Call.Return(run)
	return _c
}

// ListIndex provides a mock function with given fields: ctx, vaultID, userID
func (_m *MockSecretRepository) ListIndex(ctx context.Context, vaultID string, userID string) ([]domain.Secret, error) {
	ret := _m.Called(ctx, vaultID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListIndex")
	}

	var r0 []domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Secret, error)); ok {
		return rf(ctx, vaultID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Secret); ok {
		r0 = rf(ctx, vaultID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, vaultID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_ListIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIndex'
type MockSecretRepository_ListIndex_Call struct {
	*mock.Call
}

// ListIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID string
//   - userID string
func (_e *MockSecretRepository_Expecter) ListIndex(ctx interface{}, vaultID interface{}, userID interface{}) *MockSecretRepository_ListIndex_Call {
	return &MockSecretRepository_ListIndex_Call{Call: _e.mock.On("ListIndex", ctx, vaultID, userID)}
}

func (_c *MockSecretRepository_ListIndex_Call) Run(run func(ctx context.Context, vaultID string, userID string)) *MockSecretRepository_ListIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSecretRepository_ListIndex_Call) Return(_a0 []domain.Secret, _a1 error) *MockSecretRepository_ListIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_ListIndex_Call) RunAndReturn(run func(context.Context, string, string) ([]domain.Secret, error)) *MockSecretRepository_ListIndex_Call {
	_c.Call.Return(run)
	return _c
}

// ListRow provides a mock function with given fields: ctx, vaultID, userID
func (_m *MockSecretRepository) ListRow(ctx context.Context, vaultID string, userID string) ([]domain.Secret, error) {
	ret := _m.Called(ctx, vaultID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListRow")
	}

	var r0 []domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Secret, error)); ok {
		return rf(ctx, vaultID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Secret); ok {
		r0 = rf(ctx, vaultID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, vaultID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_ListRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRow'
type MockSecretRepository_ListRow_Call struct {
	*mock.Call
}

// ListRow is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID string
//   - userID string
func (_e *MockSecretRepository_Expecter) ListRow(ctx interface{}, vaultID interface{}, userID interface{}) *MockSecretRepository_ListRow_Call {
	return &MockSecretRepository_ListRow_Call{Call: _e.mock.On("ListRow", ctx, vaultID, userID)}
}

func (_c *MockSecretRepository_ListRow_Call) Run(run func(ctx context.Context, vaultID string, userID string)) *MockSecretRepository_ListRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSecretRepository_ListRow_Call) Return(_a0 []domain.Secret, _a1 error) *MockSecretRepository_ListRow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_ListRow_Call) RunAndReturn(run func(context.Context, string, string) ([]domain.Secret, error)) *MockSecretRepository_ListRow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretRepository creates a new instance of MockSecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretRepository {
	mock := &MockSecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
