// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockVaultOwnership is an autogenerated mock type for the VaultOwnership type
type MockVaultOwnership struct {
	mock.Mock
}

type MockVaultOwnership_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVaultOwnership) EXPECT() *MockVaultOwnership_Expecter {
	return &MockVaultOwnership_Expecter{mock: &_m.Mock}
}

// IsOwner provides a mock function with given fields: ctx, vaultID, userID
func (_m *MockVaultOwnership) IsOwner(ctx context.Context, vaultID string, userID string) (bool, error) {
	ret := _m.Called(ctx, vaultID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsOwner")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, vaultID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, vaultID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, vaultID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVaultOwnership_IsOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOwner'
type MockVaultOwnership_IsOwner_Call struct {
	*mock.Call
}

// IsOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID string
//   - userID string
func (_e *MockVaultOwnership_Expecter) IsOwner(ctx interface{}, vaultID interface{}, userID interface{}) *MockVaultOwnership_IsOwner_Call {
	return &MockVaultOwnership_IsOwner_Call{Call: _e.mock.On("IsOwner", ctx, vaultID, userID)}
}

func (_c *MockVaultOwnership_IsOwner_Call) Run(run func(ctx context.Context, vaultID string, userID string)) *MockVaultOwnership_IsOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockVaultOwnership_IsOwner_Call) Return(_a0 bool, _a1 error) *MockVaultOwnership_IsOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVaultOwnership_IsOwner_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockVaultOwnership_IsOwner_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVaultOwnership creates a new instance of MockVaultOwnership. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVaultOwnership(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVaultOwnership {
	mock := &MockVaultOwnership{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
