// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/aikowocki/yandex-go-final-diploma/internal/server/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSecretLookup is an autogenerated mock type for the SecretLookup type
type MockSecretLookup struct {
	mock.Mock
}

type MockSecretLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretLookup) EXPECT() *MockSecretLookup_Expecter {
	return &MockSecretLookup_Expecter{mock: &_m.Mock}
}

// GetForUpdate provides a mock function with given fields: ctx, secretID, userID
func (_m *MockSecretLookup) GetForUpdate(ctx context.Context, secretID string, userID string) (domain.Secret, error) {
	ret := _m.Called(ctx, secretID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetForUpdate")
	}

	var r0 domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Secret, error)); ok {
		return rf(ctx, secretID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Secret); ok {
		r0 = rf(ctx, secretID, userID)
	} else {
		r0 = ret.Get(0).(domain.Secret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, secretID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretLookup_GetForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForUpdate'
type MockSecretLookup_GetForUpdate_Call struct {
	*mock.Call
}

// GetForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
//   - userID string
func (_e *MockSecretLookup_Expecter) GetForUpdate(ctx interface{}, secretID interface{}, userID interface{}) *MockSecretLookup_GetForUpdate_Call {
	return &MockSecretLookup_GetForUpdate_Call{Call: _e.mock.On("GetForUpdate", ctx, secretID, userID)}
}

func (_c *MockSecretLookup_GetForUpdate_Call) Run(run func(ctx context.Context, secretID string, userID string)) *MockSecretLookup_GetForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSecretLookup_GetForUpdate_Call) Return(_a0 domain.Secret, _a1 error) *MockSecretLookup_GetForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretLookup_GetForUpdate_Call) RunAndReturn(run func(context.Context, string, string) (domain.Secret, error)) *MockSecretLookup_GetForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretLookup creates a new instance of MockSecretLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretLookup {
	mock := &MockSecretLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
