with-expecter: true
resolve-type-alias: False
disable-version-string: True 
issue-845-fix: True
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/aikowocki/yandex-go-final-diploma/internal/client/contracts:
    interfaces:
      ServerClient:
      TokenStore:
      Crypto:
  github.com/aikowocki/yandex-go-final-diploma/internal/server/usecase/auth:
    interfaces:
      UserRepository:
      TokenIssuer:
      TxManager:
