// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRecoveryRepository is an autogenerated mock type for the RecoveryRepository type
type MockRecoveryRepository struct {
	mock.Mock
}

type MockRecoveryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecoveryRepository) EXPECT() *MockRecoveryRepository_Expecter {
	return &MockRecoveryRepository_Expecter{mock: &_m.Mock}
}

// DeleteAll provides a mock function with given fields: ctx, userID
func (_m *MockRecoveryRepository) DeleteAll(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRecoveryRepository_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockRecoveryRepository_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRecoveryRepository_Expecter) DeleteAll(ctx interface{}, userID interface{}) *MockRecoveryRepository_DeleteAll_Call {
	return &MockRecoveryRepository_DeleteAll_Call{Call: _e.mock.On("DeleteAll", ctx, userID)}
}

func (_c *MockRecoveryRepository_DeleteAll_Call) Run(run func(ctx context.Context, userID string)) *MockRecoveryRepository_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRecoveryRepository_DeleteAll_Call) Return(_a0 error) *MockRecoveryRepository_DeleteAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecoveryRepository_DeleteAll_Call) RunAndReturn(run func(context.Context, string) error) *MockRecoveryRepository_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlob provides a mock function with given fields: ctx, userID, codeID
func (_m *MockRecoveryRepository) GetBlob(ctx context.Context, userID string, codeID string) ([]byte, error) {
	ret := _m.Called(ctx, userID, codeID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return rf(ctx, userID, codeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = rf(ctx, userID, codeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, codeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecoveryRepository_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type MockRecoveryRepository_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - codeID string
func (_e *MockRecoveryRepository_Expecter) GetBlob(ctx interface{}, userID interface{}, codeID interface{}) *MockRecoveryRepository_GetBlob_Call {
	return &MockRecoveryRepository_GetBlob_Call{Call: _e.mock.On("GetBlob", ctx, userID, codeID)}
}

func (_c *MockRecoveryRepository_GetBlob_Call) Run(run func(ctx context.Context, userID string, codeID string)) *MockRecoveryRepository_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRecoveryRepository_GetBlob_Call) Return(_a0 []byte, _a1 error) *MockRecoveryRepository_GetBlob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecoveryRepository_GetBlob_Call) RunAndReturn(run func(context.Context, string, string) ([]byte, error)) *MockRecoveryRepository_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function with given fields: ctx, userID, codeID
func (_m *MockRecoveryRepository) MarkUsed(ctx context.Context, userID string, codeID string) error {
	ret := _m.Called(ctx, userID, codeID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, codeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRecoveryRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockRecoveryRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - codeID string
func (_e *MockRecoveryRepository_Expecter) MarkUsed(ctx interface{}, userID interface{}, codeID interface{}) *MockRecoveryRepository_MarkUsed_Call {
	return &MockRecoveryRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, userID, codeID)}
}

func (_c *MockRecoveryRepository_MarkUsed_Call) Run(run func(ctx context.Context, userID string, codeID string)) *MockRecoveryRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRecoveryRepository_MarkUsed_Call) Return(_a0 error) *MockRecoveryRepository_MarkUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecoveryRepository_MarkUsed_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRecoveryRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}

// StoreCode provides a mock function with given fields: ctx, userID, codeID, encMasterKey
func (_m *MockRecoveryRepository) StoreCode(ctx context.Context, userID string, codeID string, encMasterKey []byte) error {
	ret := _m.Called(ctx, userID, codeID, encMasterKey)

	if len(ret) == 0 {
		panic("no return value specified for StoreCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, userID, codeID, encMasterKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRecoveryRepository_StoreCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreCode'
type MockRecoveryRepository_StoreCode_Call struct {
	*mock.Call
}

// StoreCode is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - codeID string
//   - encMasterKey []byte
func (_e *MockRecoveryRepository_Expecter) StoreCode(ctx interface{}, userID interface{}, codeID interface{}, encMasterKey interface{}) *MockRecoveryRepository_StoreCode_Call {
	return &MockRecoveryRepository_StoreCode_Call{Call: _e.mock.On("StoreCode", ctx, userID, codeID, encMasterKey)}
}

func (_c *MockRecoveryRepository_StoreCode_Call) Run(run func(ctx context.Context, userID string, codeID string, encMasterKey []byte)) *MockRecoveryRepository_StoreCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockRecoveryRepository_StoreCode_Call) Return(_a0 error) *MockRecoveryRepository_StoreCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecoveryRepository_StoreCode_Call) RunAndReturn(run func(context.Context, string, string, []byte) error) *MockRecoveryRepository_StoreCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecoveryRepository creates a new instance of MockRecoveryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecoveryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecoveryRepository {
	mock := &MockRecoveryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
