// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTokenIssuer is an autogenerated mock type for the TokenIssuer type
type MockTokenIssuer struct {
	mock.Mock
}

type MockTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIssuer) EXPECT() *MockTokenIssuer_Expecter {
	return &MockTokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: userID
func (_m *MockTokenIssuer) Issue(userID string) (string, string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - userID string
func (_e *MockTokenIssuer_Expecter) Issue(userID interface{}) *MockTokenIssuer_Issue_Call {
	return &MockTokenIssuer_Issue_Call{Call: _e.mock.On("Issue", userID)}
}

func (_c *MockTokenIssuer_Issue_Call) Run(run func(userID string)) *MockTokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) Return(access string, refresh string, err error) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(access, refresh, err)
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) RunAndReturn(run func(string) (string, string, error)) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: refreshToken
func (_m *MockTokenIssuer) Refresh(refreshToken string) (string, string, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, string, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(refreshToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenIssuer_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockTokenIssuer_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - refreshToken string
func (_e *MockTokenIssuer_Expecter) Refresh(refreshToken interface{}) *MockTokenIssuer_Refresh_Call {
	return &MockTokenIssuer_Refresh_Call{Call: _e.mock.On("Refresh", refreshToken)}
}

func (_c *MockTokenIssuer_Refresh_Call) Run(run func(refreshToken string)) *MockTokenIssuer_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenIssuer_Refresh_Call) Return(access string, refresh string, err error) *MockTokenIssuer_Refresh_Call {
	_c.Call.Return(access, refresh, err)
	return _c
}

func (_c *MockTokenIssuer_Refresh_Call) RunAndReturn(run func(string) (string, string, error)) *MockTokenIssuer_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: token
func (_m *MockTokenIssuer) Verify(token string) (string, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenIssuer_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockTokenIssuer_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - token string
func (_e *MockTokenIssuer_Expecter) Verify(token interface{}) *MockTokenIssuer_Verify_Call {
	return &MockTokenIssuer_Verify_Call{Call: _e.mock.On("Verify", token)}
}

func (_c *MockTokenIssuer_Verify_Call) Run(run func(token string)) *MockTokenIssuer_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenIssuer_Verify_Call) Return(userID string, err error) *MockTokenIssuer_Verify_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *MockTokenIssuer_Verify_Call) RunAndReturn(run func(string) (string, error)) *MockTokenIssuer_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIssuer creates a new instance of MockTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIssuer {
	mock := &MockTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
