// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockBlobStorage is an autogenerated mock type for the BlobStorage type
type MockBlobStorage struct {
	mock.Mock
}

type MockBlobStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobStorage) EXPECT() *MockBlobStorage_Expecter {
	return &MockBlobStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockBlobStorage) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlobStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBlobStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockBlobStorage_Expecter) Delete(ctx interface{}, key interface{}) *MockBlobStorage_Delete_Call {
	return &MockBlobStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockBlobStorage_Delete_Call) Run(run func(ctx context.Context, key string)) *MockBlobStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBlobStorage_Delete_Call) Return(_a0 error) *MockBlobStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlobStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockBlobStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetStream provides a mock function with given fields: ctx, key
func (_m *MockBlobStorage) GetStream(ctx context.Context, key string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetStream")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlobStorage_GetStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStream'
type MockBlobStorage_GetStream_Call struct {
	*mock.Call
}

// GetStream is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockBlobStorage_Expecter) GetStream(ctx interface{}, key interface{}) *MockBlobStorage_GetStream_Call {
	return &MockBlobStorage_GetStream_Call{Call: _e.mock.On("GetStream", ctx, key)}
}

func (_c *MockBlobStorage_GetStream_Call) Run(run func(ctx context.Context, key string)) *MockBlobStorage_GetStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBlobStorage_GetStream_Call) Return(_a0 io.ReadCloser, _a1 error) *MockBlobStorage_GetStream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlobStorage_GetStream_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockBlobStorage_GetStream_Call {
	_c.Call.Return(run)
	return _c
}

// PutChunk provides a mock function with given fields: ctx, key, r, size
func (_m *MockBlobStorage) PutChunk(ctx context.Context, key string, r io.Reader, size int64) (int64, error) {
	ret := _m.Called(ctx, key, r, size)

	if len(ret) == 0 {
		panic("no return value specified for PutChunk")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64) (int64, error)); ok {
		return rf(ctx, key, r, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64) int64); ok {
		r0 = rf(ctx, key, r, size)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, int64) error); ok {
		r1 = rf(ctx, key, r, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlobStorage_PutChunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutChunk'
type MockBlobStorage_PutChunk_Call struct {
	*mock.Call
}

// PutChunk is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - r io.Reader
//   - size int64
func (_e *MockBlobStorage_Expecter) PutChunk(ctx interface{}, key interface{}, r interface{}, size interface{}) *MockBlobStorage_PutChunk_Call {
	return &MockBlobStorage_PutChunk_Call{Call: _e.mock.On("PutChunk", ctx, key, r, size)}
}

func (_c *MockBlobStorage_PutChunk_Call) Run(run func(ctx context.Context, key string, r io.Reader, size int64)) *MockBlobStorage_PutChunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(int64))
	})
	return _c
}

func (_c *MockBlobStorage_PutChunk_Call) Return(written int64, err error) *MockBlobStorage_PutChunk_Call {
	_c.Call.Return(written, err)
	return _c
}

func (_c *MockBlobStorage_PutChunk_Call) RunAndReturn(run func(context.Context, string, io.Reader, int64) (int64, error)) *MockBlobStorage_PutChunk_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlobStorage creates a new instance of MockBlobStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobStorage {
	mock := &MockBlobStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
