// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockCipher is an autogenerated mock type for the Cipher type
type MockCipher struct {
	mock.Mock
}

type MockCipher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCipher) EXPECT() *MockCipher_Expecter {
	return &MockCipher_Expecter{mock: &_m.Mock}
}

// DecryptStruct provides a mock function with given fields: key, blob, value
func (_m *MockCipher) DecryptStruct(key []byte, blob []byte, value any) error {
	ret := _m.Called(key, blob, value)

	if len(ret) == 0 {
		panic("no return value specified for DecryptStruct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, any) error); ok {
		r0 = rf(key, blob, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCipher_DecryptStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptStruct'
type MockCipher_DecryptStruct_Call struct {
	*mock.Call
}

// DecryptStruct is a helper method to define mock.On call
//   - key []byte
//   - blob []byte
//   - value any
func (_e *MockCipher_Expecter) DecryptStruct(key interface{}, blob interface{}, value interface{}) *MockCipher_DecryptStruct_Call {
	return &MockCipher_DecryptStruct_Call{Call: _e.mock.On("DecryptStruct", key, blob, value)}
}

func (_c *MockCipher_DecryptStruct_Call) Run(run func(key []byte, blob []byte, value any)) *MockCipher_DecryptStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte), args[2].(any))
	})
	return _c
}

func (_c *MockCipher_DecryptStruct_Call) Return(_a0 error) *MockCipher_DecryptStruct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCipher_DecryptStruct_Call) RunAndReturn(run func([]byte, []byte, any) error) *MockCipher_DecryptStruct_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptStruct provides a mock function with given fields: key, value
func (_m *MockCipher) EncryptStruct(key []byte, value any) ([]byte, error) {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for EncryptStruct")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, any) ([]byte, error)); ok {
		return rf(key, value)
	}
	if rf, ok := ret.Get(0).(func([]byte, any) []byte); ok {
		r0 = rf(key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, any) error); ok {
		r1 = rf(key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCipher_EncryptStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptStruct'
type MockCipher_EncryptStruct_Call struct {
	*mock.Call
}

// EncryptStruct is a helper method to define mock.On call
//   - key []byte
//   - value any
func (_e *MockCipher_Expecter) EncryptStruct(key interface{}, value interface{}) *MockCipher_EncryptStruct_Call {
	return &MockCipher_EncryptStruct_Call{Call: _e.mock.On("EncryptStruct", key, value)}
}

func (_c *MockCipher_EncryptStruct_Call) Run(run func(key []byte, value any)) *MockCipher_EncryptStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(any))
	})
	return _c
}

func (_c *MockCipher_EncryptStruct_Call) Return(_a0 []byte, _a1 error) *MockCipher_EncryptStruct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCipher_EncryptStruct_Call) RunAndReturn(run func([]byte, any) ([]byte, error)) *MockCipher_EncryptStruct_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateVaultKey provides a mock function with no fields
func (_m *MockCipher) GenerateVaultKey() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateVaultKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCipher_GenerateVaultKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateVaultKey'
type MockCipher_GenerateVaultKey_Call struct {
	*mock.Call
}

// GenerateVaultKey is a helper method to define mock.On call
func (_e *MockCipher_Expecter) GenerateVaultKey() *MockCipher_GenerateVaultKey_Call {
	return &MockCipher_GenerateVaultKey_Call{Call: _e.mock.On("GenerateVaultKey")}
}

func (_c *MockCipher_GenerateVaultKey_Call) Run(run func()) *MockCipher_GenerateVaultKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCipher_GenerateVaultKey_Call) Return(_a0 []byte, _a1 error) *MockCipher_GenerateVaultKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCipher_GenerateVaultKey_Call) RunAndReturn(run func() ([]byte, error)) *MockCipher_GenerateVaultKey_Call {
	_c.Call.Return(run)
	return _c
}

// UnwrapVaultKey provides a mock function with given fields: wrapped, masterKey
func (_m *MockCipher) UnwrapVaultKey(wrapped []byte, masterKey []byte) ([]byte, error) {
	ret := _m.Called(wrapped, masterKey)

	if len(ret) == 0 {
		panic("no return value specified for UnwrapVaultKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) ([]byte, error)); ok {
		return rf(wrapped, masterKey)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(wrapped, masterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(wrapped, masterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCipher_UnwrapVaultKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnwrapVaultKey'
type MockCipher_UnwrapVaultKey_Call struct {
	*mock.Call
}

// UnwrapVaultKey is a helper method to define mock.On call
//   - wrapped []byte
//   - masterKey []byte
func (_e *MockCipher_Expecter) UnwrapVaultKey(wrapped interface{}, masterKey interface{}) *MockCipher_UnwrapVaultKey_Call {
	return &MockCipher_UnwrapVaultKey_Call{Call: _e.mock.On("UnwrapVaultKey", wrapped, masterKey)}
}

func (_c *MockCipher_UnwrapVaultKey_Call) Run(run func(wrapped []byte, masterKey []byte)) *MockCipher_UnwrapVaultKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte))
	})
	return _c
}

func (_c *MockCipher_UnwrapVaultKey_Call) Return(vaultKey []byte, err error) *MockCipher_UnwrapVaultKey_Call {
	_c.Call.Return(vaultKey, err)
	return _c
}

func (_c *MockCipher_UnwrapVaultKey_Call) RunAndReturn(run func([]byte, []byte) ([]byte, error)) *MockCipher_UnwrapVaultKey_Call {
	_c.Call.Return(run)
	return _c
}

// WrapVaultKey provides a mock function with given fields: vaultKey, masterKey
func (_m *MockCipher) WrapVaultKey(vaultKey []byte, masterKey []byte) ([]byte, error) {
	ret := _m.Called(vaultKey, masterKey)

	if len(ret) == 0 {
		panic("no return value specified for WrapVaultKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) ([]byte, error)); ok {
		return rf(vaultKey, masterKey)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(vaultKey, masterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(vaultKey, masterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCipher_WrapVaultKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WrapVaultKey'
type MockCipher_WrapVaultKey_Call struct {
	*mock.Call
}

// WrapVaultKey is a helper method to define mock.On call
//   - vaultKey []byte
//   - masterKey []byte
func (_e *MockCipher_Expecter) WrapVaultKey(vaultKey interface{}, masterKey interface{}) *MockCipher_WrapVaultKey_Call {
	return &MockCipher_WrapVaultKey_Call{Call: _e.mock.On("WrapVaultKey", vaultKey, masterKey)}
}

func (_c *MockCipher_WrapVaultKey_Call) Run(run func(vaultKey []byte, masterKey []byte)) *MockCipher_WrapVaultKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte))
	})
	return _c
}

func (_c *MockCipher_WrapVaultKey_Call) Return(wrapped []byte, err error) *MockCipher_WrapVaultKey_Call {
	_c.Call.Return(wrapped, err)
	return _c
}

func (_c *MockCipher_WrapVaultKey_Call) RunAndReturn(run func([]byte, []byte) ([]byte, error)) *MockCipher_WrapVaultKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCipher creates a new instance of MockCipher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCipher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCipher {
	mock := &MockCipher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
