// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "github.com/aikowocki/yandex-go-final-diploma/internal/client/domain"
	crypto "github.com/aikowocki/yandex-go-final-diploma/pkg/crypto"

	mock "github.com/stretchr/testify/mock"
)

// MockCrypto is an autogenerated mock type for the Crypto type
type MockCrypto struct {
	mock.Mock
}

type MockCrypto_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCrypto) EXPECT() *MockCrypto_Expecter {
	return &MockCrypto_Expecter{mock: &_m.Mock}
}

// DeriveMasterKey provides a mock function with given fields: masterSeed
func (_m *MockCrypto) DeriveMasterKey(masterSeed []byte) ([]byte, error) {
	ret := _m.Called(masterSeed)

	if len(ret) == 0 {
		panic("no return value specified for DeriveMasterKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(masterSeed)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(masterSeed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(masterSeed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCrypto_DeriveMasterKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeriveMasterKey'
type MockCrypto_DeriveMasterKey_Call struct {
	*mock.Call
}

// DeriveMasterKey is a helper method to define mock.On call
//   - masterSeed []byte
func (_e *MockCrypto_Expecter) DeriveMasterKey(masterSeed interface{}) *MockCrypto_DeriveMasterKey_Call {
	return &MockCrypto_DeriveMasterKey_Call{Call: _e.mock.On("DeriveMasterKey", masterSeed)}
}

func (_c *MockCrypto_DeriveMasterKey_Call) Run(run func(masterSeed []byte)) *MockCrypto_DeriveMasterKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockCrypto_DeriveMasterKey_Call) Return(_a0 []byte, _a1 error) *MockCrypto_DeriveMasterKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCrypto_DeriveMasterKey_Call) RunAndReturn(run func([]byte) ([]byte, error)) *MockCrypto_DeriveMasterKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeriveMasterSeed provides a mock function with given fields: key, salt, params
func (_m *MockCrypto) DeriveMasterSeed(key domain.EncryptionPassphrase, salt []byte, params crypto.Params) ([]byte, error) {
	ret := _m.Called(key, salt, params)

	if len(ret) == 0 {
		panic("no return value specified for DeriveMasterSeed")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.EncryptionPassphrase, []byte, crypto.Params) ([]byte, error)); ok {
		return rf(key, salt, params)
	}
	if rf, ok := ret.Get(0).(func(domain.EncryptionPassphrase, []byte, crypto.Params) []byte); ok {
		r0 = rf(key, salt, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.EncryptionPassphrase, []byte, crypto.Params) error); ok {
		r1 = rf(key, salt, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCrypto_DeriveMasterSeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeriveMasterSeed'
type MockCrypto_DeriveMasterSeed_Call struct {
	*mock.Call
}

// DeriveMasterSeed is a helper method to define mock.On call
//   - key domain.EncryptionPassphrase
//   - salt []byte
//   - params crypto.Params
func (_e *MockCrypto_Expecter) DeriveMasterSeed(key interface{}, salt interface{}, params interface{}) *MockCrypto_DeriveMasterSeed_Call {
	return &MockCrypto_DeriveMasterSeed_Call{Call: _e.mock.On("DeriveMasterSeed", key, salt, params)}
}

func (_c *MockCrypto_DeriveMasterSeed_Call) Run(run func(key domain.EncryptionPassphrase, salt []byte, params crypto.Params)) *MockCrypto_DeriveMasterSeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.EncryptionPassphrase), args[1].([]byte), args[2].(crypto.Params))
	})
	return _c
}

func (_c *MockCrypto_DeriveMasterSeed_Call) Return(_a0 []byte, _a1 error) *MockCrypto_DeriveMasterSeed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCrypto_DeriveMasterSeed_Call) RunAndReturn(run func(domain.EncryptionPassphrase, []byte, crypto.Params) ([]byte, error)) *MockCrypto_DeriveMasterSeed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCrypto creates a new instance of MockCrypto. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCrypto(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCrypto {
	mock := &MockCrypto{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
