// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	contracts "github.com/aikowocki/yandex-go-final-diploma/internal/client/contracts"
	mock "github.com/stretchr/testify/mock"
)

// MockLocalStorage is an autogenerated mock type for the LocalStorage type
type MockLocalStorage struct {
	mock.Mock
}

type MockLocalStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocalStorage) EXPECT() *MockLocalStorage_Expecter {
	return &MockLocalStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockLocalStorage) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockLocalStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockLocalStorage_Expecter) Close() *MockLocalStorage_Close_Call {
	return &MockLocalStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockLocalStorage_Close_Call) Run(run func()) *MockLocalStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLocalStorage_Close_Call) Return(_a0 error) *MockLocalStorage_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_Close_Call) RunAndReturn(run func() error) *MockLocalStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, id
func (_m *MockLocalStorage) DeleteSecret(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockLocalStorage_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLocalStorage_Expecter) DeleteSecret(ctx interface{}, id interface{}) *MockLocalStorage_DeleteSecret_Call {
	return &MockLocalStorage_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, id)}
}

func (_c *MockLocalStorage_DeleteSecret_Call) Run(run func(ctx context.Context, id string)) *MockLocalStorage_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLocalStorage_DeleteSecret_Call) Return(_a0 error) *MockLocalStorage_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_DeleteSecret_Call) RunAndReturn(run func(context.Context, string) error) *MockLocalStorage_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVault provides a mock function with given fields: ctx, id
func (_m *MockLocalStorage) DeleteVault(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_DeleteVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVault'
type MockLocalStorage_DeleteVault_Call struct {
	*mock.Call
}

// DeleteVault is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLocalStorage_Expecter) DeleteVault(ctx interface{}, id interface{}) *MockLocalStorage_DeleteVault_Call {
	return &MockLocalStorage_DeleteVault_Call{Call: _e.mock.On("DeleteVault", ctx, id)}
}

func (_c *MockLocalStorage_DeleteVault_Call) Run(run func(ctx context.Context, id string)) *MockLocalStorage_DeleteVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLocalStorage_DeleteVault_Call) Return(_a0 error) *MockLocalStorage_DeleteVault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_DeleteVault_Call) RunAndReturn(run func(context.Context, string) error) *MockLocalStorage_DeleteVault_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueOutbox provides a mock function with given fields: ctx, e
func (_m *MockLocalStorage) EnqueueOutbox(ctx context.Context, e contracts.OutboxEntry) (int64, error) {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueOutbox")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.OutboxEntry) (int64, error)); ok {
		return rf(ctx, e)
	}
	if rf, ok := ret.Get(0).(func(context.Context, contracts.OutboxEntry) int64); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, contracts.OutboxEntry) error); ok {
		r1 = rf(ctx, e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocalStorage_EnqueueOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueOutbox'
type MockLocalStorage_EnqueueOutbox_Call struct {
	*mock.Call
}

// EnqueueOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - e contracts.OutboxEntry
func (_e *MockLocalStorage_Expecter) EnqueueOutbox(ctx interface{}, e interface{}) *MockLocalStorage_EnqueueOutbox_Call {
	return &MockLocalStorage_EnqueueOutbox_Call{Call: _e.mock.On("EnqueueOutbox", ctx, e)}
}

func (_c *MockLocalStorage_EnqueueOutbox_Call) Run(run func(ctx context.Context, e contracts.OutboxEntry)) *MockLocalStorage_EnqueueOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(contracts.OutboxEntry))
	})
	return _c
}

func (_c *MockLocalStorage_EnqueueOutbox_Call) Return(_a0 int64, _a1 error) *MockLocalStorage_EnqueueOutbox_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocalStorage_EnqueueOutbox_Call) RunAndReturn(run func(context.Context, contracts.OutboxEntry) (int64, error)) *MockLocalStorage_EnqueueOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetOutbox provides a mock function with given fields: ctx, id
func (_m *MockLocalStorage) GetOutbox(ctx context.Context, id int64) (contracts.OutboxEntry, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOutbox")
	}

	var r0 contracts.OutboxEntry
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (contracts.OutboxEntry, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) contracts.OutboxEntry); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(contracts.OutboxEntry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLocalStorage_GetOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOutbox'
type MockLocalStorage_GetOutbox_Call struct {
	*mock.Call
}

// GetOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockLocalStorage_Expecter) GetOutbox(ctx interface{}, id interface{}) *MockLocalStorage_GetOutbox_Call {
	return &MockLocalStorage_GetOutbox_Call{Call: _e.mock.On("GetOutbox", ctx, id)}
}

func (_c *MockLocalStorage_GetOutbox_Call) Run(run func(ctx context.Context, id int64)) *MockLocalStorage_GetOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockLocalStorage_GetOutbox_Call) Return(_a0 contracts.OutboxEntry, _a1 bool, _a2 error) *MockLocalStorage_GetOutbox_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLocalStorage_GetOutbox_Call) RunAndReturn(run func(context.Context, int64) (contracts.OutboxEntry, bool, error)) *MockLocalStorage_GetOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: ctx, id
func (_m *MockLocalStorage) GetSecret(ctx context.Context, id string) (contracts.LocalSecret, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 contracts.LocalSecret
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (contracts.LocalSecret, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) contracts.LocalSecret); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(contracts.LocalSecret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLocalStorage_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockLocalStorage_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLocalStorage_Expecter) GetSecret(ctx interface{}, id interface{}) *MockLocalStorage_GetSecret_Call {
	return &MockLocalStorage_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, id)}
}

func (_c *MockLocalStorage_GetSecret_Call) Run(run func(ctx context.Context, id string)) *MockLocalStorage_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLocalStorage_GetSecret_Call) Return(_a0 contracts.LocalSecret, _a1 bool, _a2 error) *MockLocalStorage_GetSecret_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLocalStorage_GetSecret_Call) RunAndReturn(run func(context.Context, string) (contracts.LocalSecret, bool, error)) *MockLocalStorage_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetVault provides a mock function with given fields: ctx, id
func (_m *MockLocalStorage) GetVault(ctx context.Context, id string) (contracts.LocalVault, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVault")
	}

	var r0 contracts.LocalVault
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (contracts.LocalVault, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) contracts.LocalVault); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(contracts.LocalVault)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLocalStorage_GetVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVault'
type MockLocalStorage_GetVault_Call struct {
	*mock.Call
}

// GetVault is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLocalStorage_Expecter) GetVault(ctx interface{}, id interface{}) *MockLocalStorage_GetVault_Call {
	return &MockLocalStorage_GetVault_Call{Call: _e.mock.On("GetVault", ctx, id)}
}

func (_c *MockLocalStorage_GetVault_Call) Run(run func(ctx context.Context, id string)) *MockLocalStorage_GetVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLocalStorage_GetVault_Call) Return(_a0 contracts.LocalVault, _a1 bool, _a2 error) *MockLocalStorage_GetVault_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLocalStorage_GetVault_Call) RunAndReturn(run func(context.Context, string) (contracts.LocalVault, bool, error)) *MockLocalStorage_GetVault_Call {
	_c.Call.Return(run)
	return _c
}

// KVGet provides a mock function with given fields: ctx, key
func (_m *MockLocalStorage) KVGet(ctx context.Context, key string) ([]byte, bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for KVGet")
	}

	var r0 []byte
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLocalStorage_KVGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KVGet'
type MockLocalStorage_KVGet_Call struct {
	*mock.Call
}

// KVGet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockLocalStorage_Expecter) KVGet(ctx interface{}, key interface{}) *MockLocalStorage_KVGet_Call {
	return &MockLocalStorage_KVGet_Call{Call: _e.mock.On("KVGet", ctx, key)}
}

func (_c *MockLocalStorage_KVGet_Call) Run(run func(ctx context.Context, key string)) *MockLocalStorage_KVGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLocalStorage_KVGet_Call) Return(_a0 []byte, _a1 bool, _a2 error) *MockLocalStorage_KVGet_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLocalStorage_KVGet_Call) RunAndReturn(run func(context.Context, string) ([]byte, bool, error)) *MockLocalStorage_KVGet_Call {
	_c.Call.Return(run)
	return _c
}

// KVSet provides a mock function with given fields: ctx, key, value
func (_m *MockLocalStorage) KVSet(ctx context.Context, key string, value []byte) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for KVSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_KVSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KVSet'
type MockLocalStorage_KVSet_Call struct {
	*mock.Call
}

// KVSet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
func (_e *MockLocalStorage_Expecter) KVSet(ctx interface{}, key interface{}, value interface{}) *MockLocalStorage_KVSet_Call {
	return &MockLocalStorage_KVSet_Call{Call: _e.mock.On("KVSet", ctx, key, value)}
}

func (_c *MockLocalStorage_KVSet_Call) Run(run func(ctx context.Context, key string, value []byte)) *MockLocalStorage_KVSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockLocalStorage_KVSet_Call) Return(_a0 error) *MockLocalStorage_KVSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_KVSet_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockLocalStorage_KVSet_Call {
	_c.Call.Return(run)
	return _c
}

// ListOutboxByStatus provides a mock function with given fields: ctx, status
func (_m *MockLocalStorage) ListOutboxByStatus(ctx context.Context, status contracts.OutboxStatus) ([]contracts.OutboxEntry, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for ListOutboxByStatus")
	}

	var r0 []contracts.OutboxEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.OutboxStatus) ([]contracts.OutboxEntry, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, contracts.OutboxStatus) []contracts.OutboxEntry); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.OutboxEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, contracts.OutboxStatus) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocalStorage_ListOutboxByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOutboxByStatus'
type MockLocalStorage_ListOutboxByStatus_Call struct {
	*mock.Call
}

// ListOutboxByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status contracts.OutboxStatus
func (_e *MockLocalStorage_Expecter) ListOutboxByStatus(ctx interface{}, status interface{}) *MockLocalStorage_ListOutboxByStatus_Call {
	return &MockLocalStorage_ListOutboxByStatus_Call{Call: _e.mock.On("ListOutboxByStatus", ctx, status)}
}

func (_c *MockLocalStorage_ListOutboxByStatus_Call) Run(run func(ctx context.Context, status contracts.OutboxStatus)) *MockLocalStorage_ListOutboxByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(contracts.OutboxStatus))
	})
	return _c
}

func (_c *MockLocalStorage_ListOutboxByStatus_Call) Return(_a0 []contracts.OutboxEntry, _a1 error) *MockLocalStorage_ListOutboxByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocalStorage_ListOutboxByStatus_Call) RunAndReturn(run func(context.Context, contracts.OutboxStatus) ([]contracts.OutboxEntry, error)) *MockLocalStorage_ListOutboxByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingOutbox provides a mock function with given fields: ctx
func (_m *MockLocalStorage) ListPendingOutbox(ctx context.Context) ([]contracts.OutboxEntry, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingOutbox")
	}

	var r0 []contracts.OutboxEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]contracts.OutboxEntry, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []contracts.OutboxEntry); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.OutboxEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocalStorage_ListPendingOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingOutbox'
type MockLocalStorage_ListPendingOutbox_Call struct {
	*mock.Call
}

// ListPendingOutbox is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLocalStorage_Expecter) ListPendingOutbox(ctx interface{}) *MockLocalStorage_ListPendingOutbox_Call {
	return &MockLocalStorage_ListPendingOutbox_Call{Call: _e.mock.On("ListPendingOutbox", ctx)}
}

func (_c *MockLocalStorage_ListPendingOutbox_Call) Run(run func(ctx context.Context)) *MockLocalStorage_ListPendingOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLocalStorage_ListPendingOutbox_Call) Return(_a0 []contracts.OutboxEntry, _a1 error) *MockLocalStorage_ListPendingOutbox_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocalStorage_ListPendingOutbox_Call) RunAndReturn(run func(context.Context) ([]contracts.OutboxEntry, error)) *MockLocalStorage_ListPendingOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecretsByVault provides a mock function with given fields: ctx, vaultID
func (_m *MockLocalStorage) ListSecretsByVault(ctx context.Context, vaultID string) ([]contracts.LocalSecret, error) {
	ret := _m.Called(ctx, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for ListSecretsByVault")
	}

	var r0 []contracts.LocalSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]contracts.LocalSecret, error)); ok {
		return rf(ctx, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []contracts.LocalSecret); ok {
		r0 = rf(ctx, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.LocalSecret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocalStorage_ListSecretsByVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecretsByVault'
type MockLocalStorage_ListSecretsByVault_Call struct {
	*mock.Call
}

// ListSecretsByVault is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID string
func (_e *MockLocalStorage_Expecter) ListSecretsByVault(ctx interface{}, vaultID interface{}) *MockLocalStorage_ListSecretsByVault_Call {
	return &MockLocalStorage_ListSecretsByVault_Call{Call: _e.mock.On("ListSecretsByVault", ctx, vaultID)}
}

func (_c *MockLocalStorage_ListSecretsByVault_Call) Run(run func(ctx context.Context, vaultID string)) *MockLocalStorage_ListSecretsByVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLocalStorage_ListSecretsByVault_Call) Return(_a0 []contracts.LocalSecret, _a1 error) *MockLocalStorage_ListSecretsByVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocalStorage_ListSecretsByVault_Call) RunAndReturn(run func(context.Context, string) ([]contracts.LocalSecret, error)) *MockLocalStorage_ListSecretsByVault_Call {
	_c.Call.Return(run)
	return _c
}

// ListVaults provides a mock function with given fields: ctx
func (_m *MockLocalStorage) ListVaults(ctx context.Context) ([]contracts.LocalVault, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListVaults")
	}

	var r0 []contracts.LocalVault
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]contracts.LocalVault, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []contracts.LocalVault); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.LocalVault)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocalStorage_ListVaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVaults'
type MockLocalStorage_ListVaults_Call struct {
	*mock.Call
}

// ListVaults is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLocalStorage_Expecter) ListVaults(ctx interface{}) *MockLocalStorage_ListVaults_Call {
	return &MockLocalStorage_ListVaults_Call{Call: _e.mock.On("ListVaults", ctx)}
}

func (_c *MockLocalStorage_ListVaults_Call) Run(run func(ctx context.Context)) *MockLocalStorage_ListVaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLocalStorage_ListVaults_Call) Return(_a0 []contracts.LocalVault, _a1 error) *MockLocalStorage_ListVaults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocalStorage_ListVaults_Call) RunAndReturn(run func(context.Context) ([]contracts.LocalVault, error)) *MockLocalStorage_ListVaults_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveOutbox provides a mock function with given fields: ctx, id
func (_m *MockLocalStorage) RemoveOutbox(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveOutbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_RemoveOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveOutbox'
type MockLocalStorage_RemoveOutbox_Call struct {
	*mock.Call
}

// RemoveOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockLocalStorage_Expecter) RemoveOutbox(ctx interface{}, id interface{}) *MockLocalStorage_RemoveOutbox_Call {
	return &MockLocalStorage_RemoveOutbox_Call{Call: _e.mock.On("RemoveOutbox", ctx, id)}
}

func (_c *MockLocalStorage_RemoveOutbox_Call) Run(run func(ctx context.Context, id int64)) *MockLocalStorage_RemoveOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockLocalStorage_RemoveOutbox_Call) Return(_a0 error) *MockLocalStorage_RemoveOutbox_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_RemoveOutbox_Call) RunAndReturn(run func(context.Context, int64) error) *MockLocalStorage_RemoveOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// SetOutboxStatus provides a mock function with given fields: ctx, id, status
func (_m *MockLocalStorage) SetOutboxStatus(ctx context.Context, id int64, status contracts.OutboxStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for SetOutboxStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, contracts.OutboxStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_SetOutboxStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOutboxStatus'
type MockLocalStorage_SetOutboxStatus_Call struct {
	*mock.Call
}

// SetOutboxStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - status contracts.OutboxStatus
func (_e *MockLocalStorage_Expecter) SetOutboxStatus(ctx interface{}, id interface{}, status interface{}) *MockLocalStorage_SetOutboxStatus_Call {
	return &MockLocalStorage_SetOutboxStatus_Call{Call: _e.mock.On("SetOutboxStatus", ctx, id, status)}
}

func (_c *MockLocalStorage_SetOutboxStatus_Call) Run(run func(ctx context.Context, id int64, status contracts.OutboxStatus)) *MockLocalStorage_SetOutboxStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(contracts.OutboxStatus))
	})
	return _c
}

func (_c *MockLocalStorage_SetOutboxStatus_Call) Return(_a0 error) *MockLocalStorage_SetOutboxStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_SetOutboxStatus_Call) RunAndReturn(run func(context.Context, int64, contracts.OutboxStatus) error) *MockLocalStorage_SetOutboxStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetSecretIndex provides a mock function with given fields: ctx, id, encIndex, version
func (_m *MockLocalStorage) SetSecretIndex(ctx context.Context, id string, encIndex []byte, version int64) error {
	ret := _m.Called(ctx, id, encIndex, version)

	if len(ret) == 0 {
		panic("no return value specified for SetSecretIndex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, int64) error); ok {
		r0 = rf(ctx, id, encIndex, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_SetSecretIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSecretIndex'
type MockLocalStorage_SetSecretIndex_Call struct {
	*mock.Call
}

// SetSecretIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - encIndex []byte
//   - version int64
func (_e *MockLocalStorage_Expecter) SetSecretIndex(ctx interface{}, id interface{}, encIndex interface{}, version interface{}) *MockLocalStorage_SetSecretIndex_Call {
	return &MockLocalStorage_SetSecretIndex_Call{Call: _e.mock.On("SetSecretIndex", ctx, id, encIndex, version)}
}

func (_c *MockLocalStorage_SetSecretIndex_Call) Run(run func(ctx context.Context, id string, encIndex []byte, version int64)) *MockLocalStorage_SetSecretIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(int64))
	})
	return _c
}

func (_c *MockLocalStorage_SetSecretIndex_Call) Return(_a0 error) *MockLocalStorage_SetSecretIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_SetSecretIndex_Call) RunAndReturn(run func(context.Context, string, []byte, int64) error) *MockLocalStorage_SetSecretIndex_Call {
	_c.Call.Return(run)
	return _c
}

// SetSecretPayload provides a mock function with given fields: ctx, id, encPayload, version
func (_m *MockLocalStorage) SetSecretPayload(ctx context.Context, id string, encPayload []byte, version int64) error {
	ret := _m.Called(ctx, id, encPayload, version)

	if len(ret) == 0 {
		panic("no return value specified for SetSecretPayload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, int64) error); ok {
		r0 = rf(ctx, id, encPayload, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_SetSecretPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSecretPayload'
type MockLocalStorage_SetSecretPayload_Call struct {
	*mock.Call
}

// SetSecretPayload is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - encPayload []byte
//   - version int64
func (_e *MockLocalStorage_Expecter) SetSecretPayload(ctx interface{}, id interface{}, encPayload interface{}, version interface{}) *MockLocalStorage_SetSecretPayload_Call {
	return &MockLocalStorage_SetSecretPayload_Call{Call: _e.mock.On("SetSecretPayload", ctx, id, encPayload, version)}
}

func (_c *MockLocalStorage_SetSecretPayload_Call) Run(run func(ctx context.Context, id string, encPayload []byte, version int64)) *MockLocalStorage_SetSecretPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(int64))
	})
	return _c
}

func (_c *MockLocalStorage_SetSecretPayload_Call) Return(_a0 error) *MockLocalStorage_SetSecretPayload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_SetSecretPayload_Call) RunAndReturn(run func(context.Context, string, []byte, int64) error) *MockLocalStorage_SetSecretPayload_Call {
	_c.Call.Return(run)
	return _c
}

// SetVaultSyncEnabled provides a mock function with given fields: ctx, id, enabled
func (_m *MockLocalStorage) SetVaultSyncEnabled(ctx context.Context, id string, enabled bool) error {
	ret := _m.Called(ctx, id, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetVaultSyncEnabled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, id, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_SetVaultSyncEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVaultSyncEnabled'
type MockLocalStorage_SetVaultSyncEnabled_Call struct {
	*mock.Call
}

// SetVaultSyncEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - enabled bool
func (_e *MockLocalStorage_Expecter) SetVaultSyncEnabled(ctx interface{}, id interface{}, enabled interface{}) *MockLocalStorage_SetVaultSyncEnabled_Call {
	return &MockLocalStorage_SetVaultSyncEnabled_Call{Call: _e.mock.On("SetVaultSyncEnabled", ctx, id, enabled)}
}

func (_c *MockLocalStorage_SetVaultSyncEnabled_Call) Run(run func(ctx context.Context, id string, enabled bool)) *MockLocalStorage_SetVaultSyncEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockLocalStorage_SetVaultSyncEnabled_Call) Return(_a0 error) *MockLocalStorage_SetVaultSyncEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_SetVaultSyncEnabled_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockLocalStorage_SetVaultSyncEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// SetVaultSyncedVersion provides a mock function with given fields: ctx, id, syncedVersion
func (_m *MockLocalStorage) SetVaultSyncedVersion(ctx context.Context, id string, syncedVersion int64) error {
	ret := _m.Called(ctx, id, syncedVersion)

	if len(ret) == 0 {
		panic("no return value specified for SetVaultSyncedVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, id, syncedVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_SetVaultSyncedVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVaultSyncedVersion'
type MockLocalStorage_SetVaultSyncedVersion_Call struct {
	*mock.Call
}

// SetVaultSyncedVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - syncedVersion int64
func (_e *MockLocalStorage_Expecter) SetVaultSyncedVersion(ctx interface{}, id interface{}, syncedVersion interface{}) *MockLocalStorage_SetVaultSyncedVersion_Call {
	return &MockLocalStorage_SetVaultSyncedVersion_Call{Call: _e.mock.On("SetVaultSyncedVersion", ctx, id, syncedVersion)}
}

func (_c *MockLocalStorage_SetVaultSyncedVersion_Call) Run(run func(ctx context.Context, id string, syncedVersion int64)) *MockLocalStorage_SetVaultSyncedVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockLocalStorage_SetVaultSyncedVersion_Call) Return(_a0 error) *MockLocalStorage_SetVaultSyncedVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_SetVaultSyncedVersion_Call) RunAndReturn(run func(context.Context, string, int64) error) *MockLocalStorage_SetVaultSyncedVersion_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertSecretRow provides a mock function with given fields: ctx, s
func (_m *MockLocalStorage) UpsertSecretRow(ctx context.Context, s contracts.LocalSecret) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSecretRow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.LocalSecret) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_UpsertSecretRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSecretRow'
type MockLocalStorage_UpsertSecretRow_Call struct {
	*mock.Call
}

// UpsertSecretRow is a helper method to define mock.On call
//   - ctx context.Context
//   - s contracts.LocalSecret
func (_e *MockLocalStorage_Expecter) UpsertSecretRow(ctx interface{}, s interface{}) *MockLocalStorage_UpsertSecretRow_Call {
	return &MockLocalStorage_UpsertSecretRow_Call{Call: _e.mock.On("UpsertSecretRow", ctx, s)}
}

func (_c *MockLocalStorage_UpsertSecretRow_Call) Run(run func(ctx context.Context, s contracts.LocalSecret)) *MockLocalStorage_UpsertSecretRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(contracts.LocalSecret))
	})
	return _c
}

func (_c *MockLocalStorage_UpsertSecretRow_Call) Return(_a0 error) *MockLocalStorage_UpsertSecretRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_UpsertSecretRow_Call) RunAndReturn(run func(context.Context, contracts.LocalSecret) error) *MockLocalStorage_UpsertSecretRow_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertVault provides a mock function with given fields: ctx, v
func (_m *MockLocalStorage) UpsertVault(ctx context.Context, v contracts.LocalVault) error {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for UpsertVault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.LocalVault) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_UpsertVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertVault'
type MockLocalStorage_UpsertVault_Call struct {
	*mock.Call
}

// UpsertVault is a helper method to define mock.On call
//   - ctx context.Context
//   - v contracts.LocalVault
func (_e *MockLocalStorage_Expecter) UpsertVault(ctx interface{}, v interface{}) *MockLocalStorage_UpsertVault_Call {
	return &MockLocalStorage_UpsertVault_Call{Call: _e.mock.On("UpsertVault", ctx, v)}
}

func (_c *MockLocalStorage_UpsertVault_Call) Run(run func(ctx context.Context, v contracts.LocalVault)) *MockLocalStorage_UpsertVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(contracts.LocalVault))
	})
	return _c
}

func (_c *MockLocalStorage_UpsertVault_Call) Return(_a0 error) *MockLocalStorage_UpsertVault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_UpsertVault_Call) RunAndReturn(run func(context.Context, contracts.LocalVault) error) *MockLocalStorage_UpsertVault_Call {
	_c.Call.Return(run)
	return _c
}

// WipeAccountData provides a mock function with given fields: ctx
func (_m *MockLocalStorage) WipeAccountData(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WipeAccountData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocalStorage_WipeAccountData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WipeAccountData'
type MockLocalStorage_WipeAccountData_Call struct {
	*mock.Call
}

// WipeAccountData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLocalStorage_Expecter) WipeAccountData(ctx interface{}) *MockLocalStorage_WipeAccountData_Call {
	return &MockLocalStorage_WipeAccountData_Call{Call: _e.mock.On("WipeAccountData", ctx)}
}

func (_c *MockLocalStorage_WipeAccountData_Call) Run(run func(ctx context.Context)) *MockLocalStorage_WipeAccountData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLocalStorage_WipeAccountData_Call) Return(_a0 error) *MockLocalStorage_WipeAccountData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocalStorage_WipeAccountData_Call) RunAndReturn(run func(context.Context) error) *MockLocalStorage_WipeAccountData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLocalStorage creates a new instance of MockLocalStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocalStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocalStorage {
	mock := &MockLocalStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
