// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	contracts "github.com/aikowocki/yandex-go-final-diploma/internal/client/contracts"

	mock "github.com/stretchr/testify/mock"
)

// MockServerClient is an autogenerated mock type for the ServerClient type
type MockServerClient struct {
	mock.Mock
}

type MockServerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerClient) EXPECT() *MockServerClient_Expecter {
	return &MockServerClient_Expecter{mock: &_m.Mock}
}

// AttachBlob provides a mock function with given fields: ctx, accessToken, secretID, baseVersion, blobRef, blobSize
func (_m *MockServerClient) AttachBlob(ctx context.Context, accessToken string, secretID string, baseVersion int64, blobRef string, blobSize int64) (int64, error) {
	ret := _m.Called(ctx, accessToken, secretID, baseVersion, blobRef, blobSize)

	if len(ret) == 0 {
		panic("no return value specified for AttachBlob")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, string, int64) (int64, error)); ok {
		return rf(ctx, accessToken, secretID, baseVersion, blobRef, blobSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, string, int64) int64); ok {
		r0 = rf(ctx, accessToken, secretID, baseVersion, blobRef, blobSize)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, string, int64) error); ok {
		r1 = rf(ctx, accessToken, secretID, baseVersion, blobRef, blobSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_AttachBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachBlob'
type MockServerClient_AttachBlob_Call struct {
	*mock.Call
}

// AttachBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - secretID string
//   - baseVersion int64
//   - blobRef string
//   - blobSize int64
func (_e *MockServerClient_Expecter) AttachBlob(ctx interface{}, accessToken interface{}, secretID interface{}, baseVersion interface{}, blobRef interface{}, blobSize interface{}) *MockServerClient_AttachBlob_Call {
	return &MockServerClient_AttachBlob_Call{Call: _e.mock.On("AttachBlob", ctx, accessToken, secretID, baseVersion, blobRef, blobSize)}
}

func (_c *MockServerClient_AttachBlob_Call) Run(run func(ctx context.Context, accessToken string, secretID string, baseVersion int64, blobRef string, blobSize int64)) *MockServerClient_AttachBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64), args[4].(string), args[5].(int64))
	})
	return _c
}

func (_c *MockServerClient_AttachBlob_Call) Return(newVersion int64, err error) *MockServerClient_AttachBlob_Call {
	_c.Call.Return(newVersion, err)
	return _c
}

func (_c *MockServerClient_AttachBlob_Call) RunAndReturn(run func(context.Context, string, string, int64, string, int64) (int64, error)) *MockServerClient_AttachBlob_Call {
	_c.Call.Return(run)
	return _c
}

// CheckFreshness provides a mock function with given fields: ctx, accessToken
func (_m *MockServerClient) CheckFreshness(ctx context.Context, accessToken string) ([]contracts.VaultVersion, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for CheckFreshness")
	}

	var r0 []contracts.VaultVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]contracts.VaultVersion, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []contracts.VaultVersion); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.VaultVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_CheckFreshness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckFreshness'
type MockServerClient_CheckFreshness_Call struct {
	*mock.Call
}

// CheckFreshness is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockServerClient_Expecter) CheckFreshness(ctx interface{}, accessToken interface{}) *MockServerClient_CheckFreshness_Call {
	return &MockServerClient_CheckFreshness_Call{Call: _e.mock.On("CheckFreshness", ctx, accessToken)}
}

func (_c *MockServerClient_CheckFreshness_Call) Run(run func(ctx context.Context, accessToken string)) *MockServerClient_CheckFreshness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerClient_CheckFreshness_Call) Return(_a0 []contracts.VaultVersion, _a1 error) *MockServerClient_CheckFreshness_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_CheckFreshness_Call) RunAndReturn(run func(context.Context, string) ([]contracts.VaultVersion, error)) *MockServerClient_CheckFreshness_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecret provides a mock function with given fields: ctx, accessToken, secretID, vaultID, secretType, encRow, encIndex, encPayload
func (_m *MockServerClient) CreateSecret(ctx context.Context, accessToken string, secretID string, vaultID string, secretType int32, encRow []byte, encIndex []byte, encPayload []byte) error {
	ret := _m.Called(ctx, accessToken, secretID, vaultID, secretType, encRow, encIndex, encPayload)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int32, []byte, []byte, []byte) error); ok {
		r0 = rf(ctx, accessToken, secretID, vaultID, secretType, encRow, encIndex, encPayload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerClient_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockServerClient_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - secretID string
//   - vaultID string
//   - secretType int32
//   - encRow []byte
//   - encIndex []byte
//   - encPayload []byte
func (_e *MockServerClient_Expecter) CreateSecret(ctx interface{}, accessToken interface{}, secretID interface{}, vaultID interface{}, secretType interface{}, encRow interface{}, encIndex interface{}, encPayload interface{}) *MockServerClient_CreateSecret_Call {
	return &MockServerClient_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, accessToken, secretID, vaultID, secretType, encRow, encIndex, encPayload)}
}

func (_c *MockServerClient_CreateSecret_Call) Run(run func(ctx context.Context, accessToken string, secretID string, vaultID string, secretType int32, encRow []byte, encIndex []byte, encPayload []byte)) *MockServerClient_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int32), args[5].([]byte), args[6].([]byte), args[7].([]byte))
	})
	return _c
}

func (_c *MockServerClient_CreateSecret_Call) Return(_a0 error) *MockServerClient_CreateSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerClient_CreateSecret_Call) RunAndReturn(run func(context.Context, string, string, string, int32, []byte, []byte, []byte) error) *MockServerClient_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVault provides a mock function with given fields: ctx, accessToken, wrappedVaultKey, encName
func (_m *MockServerClient) CreateVault(ctx context.Context, accessToken string, wrappedVaultKey []byte, encName []byte) (string, error) {
	ret := _m.Called(ctx, accessToken, wrappedVaultKey, encName)

	if len(ret) == 0 {
		panic("no return value specified for CreateVault")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, []byte) (string, error)); ok {
		return rf(ctx, accessToken, wrappedVaultKey, encName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, []byte) string); ok {
		r0 = rf(ctx, accessToken, wrappedVaultKey, encName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, []byte) error); ok {
		r1 = rf(ctx, accessToken, wrappedVaultKey, encName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_CreateVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVault'
type MockServerClient_CreateVault_Call struct {
	*mock.Call
}

// CreateVault is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - wrappedVaultKey []byte
//   - encName []byte
func (_e *MockServerClient_Expecter) CreateVault(ctx interface{}, accessToken interface{}, wrappedVaultKey interface{}, encName interface{}) *MockServerClient_CreateVault_Call {
	return &MockServerClient_CreateVault_Call{Call: _e.mock.On("CreateVault", ctx, accessToken, wrappedVaultKey, encName)}
}

func (_c *MockServerClient_CreateVault_Call) Run(run func(ctx context.Context, accessToken string, wrappedVaultKey []byte, encName []byte)) *MockServerClient_CreateVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].([]byte))
	})
	return _c
}

func (_c *MockServerClient_CreateVault_Call) Return(vaultID string, err error) *MockServerClient_CreateVault_Call {
	_c.Call.Return(vaultID, err)
	return _c
}

func (_c *MockServerClient_CreateVault_Call) RunAndReturn(run func(context.Context, string, []byte, []byte) (string, error)) *MockServerClient_CreateVault_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, accessToken, secretID, baseVersion
func (_m *MockServerClient) DeleteSecret(ctx context.Context, accessToken string, secretID string, baseVersion int64) error {
	ret := _m.Called(ctx, accessToken, secretID, baseVersion)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, accessToken, secretID, baseVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerClient_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockServerClient_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - secretID string
//   - baseVersion int64
func (_e *MockServerClient_Expecter) DeleteSecret(ctx interface{}, accessToken interface{}, secretID interface{}, baseVersion interface{}) *MockServerClient_DeleteSecret_Call {
	return &MockServerClient_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, accessToken, secretID, baseVersion)}
}

func (_c *MockServerClient_DeleteSecret_Call) Run(run func(ctx context.Context, accessToken string, secretID string, baseVersion int64)) *MockServerClient_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockServerClient_DeleteSecret_Call) Return(_a0 error) *MockServerClient_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerClient_DeleteSecret_Call) RunAndReturn(run func(context.Context, string, string, int64) error) *MockServerClient_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadBlob provides a mock function with given fields: ctx, accessToken, secretID
func (_m *MockServerClient) DownloadBlob(ctx context.Context, accessToken string, secretID string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, accessToken, secretID)

	if len(ret) == 0 {
		panic("no return value specified for DownloadBlob")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (io.ReadCloser, error)); ok {
		return rf(ctx, accessToken, secretID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) io.ReadCloser); ok {
		r0 = rf(ctx, accessToken, secretID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessToken, secretID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_DownloadBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadBlob'
type MockServerClient_DownloadBlob_Call struct {
	*mock.Call
}

// DownloadBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - secretID string
func (_e *MockServerClient_Expecter) DownloadBlob(ctx interface{}, accessToken interface{}, secretID interface{}) *MockServerClient_DownloadBlob_Call {
	return &MockServerClient_DownloadBlob_Call{Call: _e.mock.On("DownloadBlob", ctx, accessToken, secretID)}
}

func (_c *MockServerClient_DownloadBlob_Call) Run(run func(ctx context.Context, accessToken string, secretID string)) *MockServerClient_DownloadBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServerClient_DownloadBlob_Call) Return(_a0 io.ReadCloser, _a1 error) *MockServerClient_DownloadBlob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_DownloadBlob_Call) RunAndReturn(run func(context.Context, string, string) (io.ReadCloser, error)) *MockServerClient_DownloadBlob_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretPayload provides a mock function with given fields: ctx, accessToken, secretID
func (_m *MockServerClient) GetSecretPayload(ctx context.Context, accessToken string, secretID string) (contracts.SecretPayloadItem, error) {
	ret := _m.Called(ctx, accessToken, secretID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretPayload")
	}

	var r0 contracts.SecretPayloadItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (contracts.SecretPayloadItem, error)); ok {
		return rf(ctx, accessToken, secretID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) contracts.SecretPayloadItem); ok {
		r0 = rf(ctx, accessToken, secretID)
	} else {
		r0 = ret.Get(0).(contracts.SecretPayloadItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessToken, secretID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_GetSecretPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretPayload'
type MockServerClient_GetSecretPayload_Call struct {
	*mock.Call
}

// GetSecretPayload is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - secretID string
func (_e *MockServerClient_Expecter) GetSecretPayload(ctx interface{}, accessToken interface{}, secretID interface{}) *MockServerClient_GetSecretPayload_Call {
	return &MockServerClient_GetSecretPayload_Call{Call: _e.mock.On("GetSecretPayload", ctx, accessToken, secretID)}
}

func (_c *MockServerClient_GetSecretPayload_Call) Run(run func(ctx context.Context, accessToken string, secretID string)) *MockServerClient_GetSecretPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServerClient_GetSecretPayload_Call) Return(_a0 contracts.SecretPayloadItem, _a1 error) *MockServerClient_GetSecretPayload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_GetSecretPayload_Call) RunAndReturn(run func(context.Context, string, string) (contracts.SecretPayloadItem, error)) *MockServerClient_GetSecretPayload_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecretIndex provides a mock function with given fields: ctx, accessToken, vaultID
func (_m *MockServerClient) ListSecretIndex(ctx context.Context, accessToken string, vaultID string) ([]contracts.SecretIndexItem, error) {
	ret := _m.Called(ctx, accessToken, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for ListSecretIndex")
	}

	var r0 []contracts.SecretIndexItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]contracts.SecretIndexItem, error)); ok {
		return rf(ctx, accessToken, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []contracts.SecretIndexItem); ok {
		r0 = rf(ctx, accessToken, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.SecretIndexItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessToken, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_ListSecretIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecretIndex'
type MockServerClient_ListSecretIndex_Call struct {
	*mock.Call
}

// ListSecretIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - vaultID string
func (_e *MockServerClient_Expecter) ListSecretIndex(ctx interface{}, accessToken interface{}, vaultID interface{}) *MockServerClient_ListSecretIndex_Call {
	return &MockServerClient_ListSecretIndex_Call{Call: _e.mock.On("ListSecretIndex", ctx, accessToken, vaultID)}
}

func (_c *MockServerClient_ListSecretIndex_Call) Run(run func(ctx context.Context, accessToken string, vaultID string)) *MockServerClient_ListSecretIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServerClient_ListSecretIndex_Call) Return(_a0 []contracts.SecretIndexItem, _a1 error) *MockServerClient_ListSecretIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_ListSecretIndex_Call) RunAndReturn(run func(context.Context, string, string) ([]contracts.SecretIndexItem, error)) *MockServerClient_ListSecretIndex_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecretRows provides a mock function with given fields: ctx, accessToken, vaultID
func (_m *MockServerClient) ListSecretRows(ctx context.Context, accessToken string, vaultID string) ([]contracts.SecretRowItem, error) {
	ret := _m.Called(ctx, accessToken, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for ListSecretRows")
	}

	var r0 []contracts.SecretRowItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]contracts.SecretRowItem, error)); ok {
		return rf(ctx, accessToken, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []contracts.SecretRowItem); ok {
		r0 = rf(ctx, accessToken, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.SecretRowItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessToken, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_ListSecretRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecretRows'
type MockServerClient_ListSecretRows_Call struct {
	*mock.Call
}

// ListSecretRows is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - vaultID string
func (_e *MockServerClient_Expecter) ListSecretRows(ctx interface{}, accessToken interface{}, vaultID interface{}) *MockServerClient_ListSecretRows_Call {
	return &MockServerClient_ListSecretRows_Call{Call: _e.mock.On("ListSecretRows", ctx, accessToken, vaultID)}
}

func (_c *MockServerClient_ListSecretRows_Call) Run(run func(ctx context.Context, accessToken string, vaultID string)) *MockServerClient_ListSecretRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServerClient_ListSecretRows_Call) Return(_a0 []contracts.SecretRowItem, _a1 error) *MockServerClient_ListSecretRows_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_ListSecretRows_Call) RunAndReturn(run func(context.Context, string, string) ([]contracts.SecretRowItem, error)) *MockServerClient_ListSecretRows_Call {
	_c.Call.Return(run)
	return _c
}

// ListVaults provides a mock function with given fields: ctx, accessToken
func (_m *MockServerClient) ListVaults(ctx context.Context, accessToken string) ([]contracts.VaultItem, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ListVaults")
	}

	var r0 []contracts.VaultItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]contracts.VaultItem, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []contracts.VaultItem); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.VaultItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_ListVaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVaults'
type MockServerClient_ListVaults_Call struct {
	*mock.Call
}

// ListVaults is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockServerClient_Expecter) ListVaults(ctx interface{}, accessToken interface{}) *MockServerClient_ListVaults_Call {
	return &MockServerClient_ListVaults_Call{Call: _e.mock.On("ListVaults", ctx, accessToken)}
}

func (_c *MockServerClient_ListVaults_Call) Run(run func(ctx context.Context, accessToken string)) *MockServerClient_ListVaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerClient_ListVaults_Call) Return(_a0 []contracts.VaultItem, _a1 error) *MockServerClient_ListVaults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_ListVaults_Call) RunAndReturn(run func(context.Context, string) ([]contracts.VaultItem, error)) *MockServerClient_ListVaults_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, login, loginCredential
func (_m *MockServerClient) Login(ctx context.Context, login string, loginCredential []byte) (contracts.LoginResult, error) {
	ret := _m.Called(ctx, login, loginCredential)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 contracts.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (contracts.LoginResult, error)); ok {
		return rf(ctx, login, loginCredential)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) contracts.LoginResult); ok {
		r0 = rf(ctx, login, loginCredential)
	} else {
		r0 = ret.Get(0).(contracts.LoginResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, login, loginCredential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockServerClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - loginCredential []byte
func (_e *MockServerClient_Expecter) Login(ctx interface{}, login interface{}, loginCredential interface{}) *MockServerClient_Login_Call {
	return &MockServerClient_Login_Call{Call: _e.mock.On("Login", ctx, login, loginCredential)}
}

func (_c *MockServerClient_Login_Call) Run(run func(ctx context.Context, login string, loginCredential []byte)) *MockServerClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockServerClient_Login_Call) Return(_a0 contracts.LoginResult, _a1 error) *MockServerClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_Login_Call) RunAndReturn(run func(context.Context, string, []byte) (contracts.LoginResult, error)) *MockServerClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockServerClient) RefreshToken(ctx context.Context, refreshToken string) (contracts.LoginResult, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 contracts.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (contracts.LoginResult, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) contracts.LoginResult); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(contracts.LoginResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockServerClient_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockServerClient_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockServerClient_RefreshToken_Call {
	return &MockServerClient_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockServerClient_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockServerClient_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerClient_RefreshToken_Call) Return(_a0 contracts.LoginResult, _a1 error) *MockServerClient_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (contracts.LoginResult, error)) *MockServerClient_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, login, loginCredential
func (_m *MockServerClient) Register(ctx context.Context, login string, loginCredential []byte) (contracts.Tokens, error) {
	ret := _m.Called(ctx, login, loginCredential)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 contracts.Tokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (contracts.Tokens, error)); ok {
		return rf(ctx, login, loginCredential)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) contracts.Tokens); ok {
		r0 = rf(ctx, login, loginCredential)
	} else {
		r0 = ret.Get(0).(contracts.Tokens)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, login, loginCredential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockServerClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - loginCredential []byte
func (_e *MockServerClient_Expecter) Register(ctx interface{}, login interface{}, loginCredential interface{}) *MockServerClient_Register_Call {
	return &MockServerClient_Register_Call{Call: _e.mock.On("Register", ctx, login, loginCredential)}
}

func (_c *MockServerClient_Register_Call) Run(run func(ctx context.Context, login string, loginCredential []byte)) *MockServerClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockServerClient_Register_Call) Return(_a0 contracts.Tokens, _a1 error) *MockServerClient_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_Register_Call) RunAndReturn(run func(context.Context, string, []byte) (contracts.Tokens, error)) *MockServerClient_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SetupEncryption provides a mock function with given fields: ctx, accessToken, encKDFSalt, encKDFParams
func (_m *MockServerClient) SetupEncryption(ctx context.Context, accessToken string, encKDFSalt []byte, encKDFParams []byte) error {
	ret := _m.Called(ctx, accessToken, encKDFSalt, encKDFParams)

	if len(ret) == 0 {
		panic("no return value specified for SetupEncryption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, []byte) error); ok {
		r0 = rf(ctx, accessToken, encKDFSalt, encKDFParams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerClient_SetupEncryption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupEncryption'
type MockServerClient_SetupEncryption_Call struct {
	*mock.Call
}

// SetupEncryption is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - encKDFSalt []byte
//   - encKDFParams []byte
func (_e *MockServerClient_Expecter) SetupEncryption(ctx interface{}, accessToken interface{}, encKDFSalt interface{}, encKDFParams interface{}) *MockServerClient_SetupEncryption_Call {
	return &MockServerClient_SetupEncryption_Call{Call: _e.mock.On("SetupEncryption", ctx, accessToken, encKDFSalt, encKDFParams)}
}

func (_c *MockServerClient_SetupEncryption_Call) Run(run func(ctx context.Context, accessToken string, encKDFSalt []byte, encKDFParams []byte)) *MockServerClient_SetupEncryption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].([]byte))
	})
	return _c
}

func (_c *MockServerClient_SetupEncryption_Call) Return(_a0 error) *MockServerClient_SetupEncryption_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerClient_SetupEncryption_Call) RunAndReturn(run func(context.Context, string, []byte, []byte) error) *MockServerClient_SetupEncryption_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function with given fields: ctx, accessToken, secretID, baseVersion, encRow, encIndex, encPayload
func (_m *MockServerClient) UpdateSecret(ctx context.Context, accessToken string, secretID string, baseVersion int64, encRow []byte, encIndex []byte, encPayload []byte) (int64, error) {
	ret := _m.Called(ctx, accessToken, secretID, baseVersion, encRow, encIndex, encPayload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, []byte, []byte, []byte) (int64, error)); ok {
		return rf(ctx, accessToken, secretID, baseVersion, encRow, encIndex, encPayload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, []byte, []byte, []byte) int64); ok {
		r0 = rf(ctx, accessToken, secretID, baseVersion, encRow, encIndex, encPayload)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, []byte, []byte, []byte) error); ok {
		r1 = rf(ctx, accessToken, secretID, baseVersion, encRow, encIndex, encPayload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockServerClient_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - secretID string
//   - baseVersion int64
//   - encRow []byte
//   - encIndex []byte
//   - encPayload []byte
func (_e *MockServerClient_Expecter) UpdateSecret(ctx interface{}, accessToken interface{}, secretID interface{}, baseVersion interface{}, encRow interface{}, encIndex interface{}, encPayload interface{}) *MockServerClient_UpdateSecret_Call {
	return &MockServerClient_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, accessToken, secretID, baseVersion, encRow, encIndex, encPayload)}
}

func (_c *MockServerClient_UpdateSecret_Call) Run(run func(ctx context.Context, accessToken string, secretID string, baseVersion int64, encRow []byte, encIndex []byte, encPayload []byte)) *MockServerClient_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64), args[4].([]byte), args[5].([]byte), args[6].([]byte))
	})
	return _c
}

func (_c *MockServerClient_UpdateSecret_Call) Return(newVersion int64, err error) *MockServerClient_UpdateSecret_Call {
	_c.Call.Return(newVersion, err)
	return _c
}

func (_c *MockServerClient_UpdateSecret_Call) RunAndReturn(run func(context.Context, string, string, int64, []byte, []byte, []byte) (int64, error)) *MockServerClient_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// UploadBlob provides a mock function with given fields: ctx, accessToken, secretID, r
func (_m *MockServerClient) UploadBlob(ctx context.Context, accessToken string, secretID string, r io.Reader) (string, int64, error) {
	ret := _m.Called(ctx, accessToken, secretID, r)

	if len(ret) == 0 {
		panic("no return value specified for UploadBlob")
	}

	var r0 string
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) (string, int64, error)); ok {
		return rf(ctx, accessToken, secretID, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) string); ok {
		r0 = rf(ctx, accessToken, secretID, r)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader) int64); ok {
		r1 = rf(ctx, accessToken, secretID, r)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, io.Reader) error); ok {
		r2 = rf(ctx, accessToken, secretID, r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockServerClient_UploadBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadBlob'
type MockServerClient_UploadBlob_Call struct {
	*mock.Call
}

// UploadBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - secretID string
//   - r io.Reader
func (_e *MockServerClient_Expecter) UploadBlob(ctx interface{}, accessToken interface{}, secretID interface{}, r interface{}) *MockServerClient_UploadBlob_Call {
	return &MockServerClient_UploadBlob_Call{Call: _e.mock.On("UploadBlob", ctx, accessToken, secretID, r)}
}

func (_c *MockServerClient_UploadBlob_Call) Run(run func(ctx context.Context, accessToken string, secretID string, r io.Reader)) *MockServerClient_UploadBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(io.Reader))
	})
	return _c
}

func (_c *MockServerClient_UploadBlob_Call) Return(blobRef string, blobSize int64, err error) *MockServerClient_UploadBlob_Call {
	_c.Call.Return(blobRef, blobSize, err)
	return _c
}

func (_c *MockServerClient_UploadBlob_Call) RunAndReturn(run func(context.Context, string, string, io.Reader) (string, int64, error)) *MockServerClient_UploadBlob_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerClient creates a new instance of MockServerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerClient {
	mock := &MockServerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
