// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	contracts "github.com/aikowocki/yandex-go-final-diploma/internal/client/contracts"
	mock "github.com/stretchr/testify/mock"
)

// MockServerClient is an autogenerated mock type for the ServerClient type
type MockServerClient struct {
	mock.Mock
}

type MockServerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerClient) EXPECT() *MockServerClient_Expecter {
	return &MockServerClient_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, login, loginCredential
func (_m *MockServerClient) Login(ctx context.Context, login string, loginCredential []byte) (contracts.LoginResult, error) {
	ret := _m.Called(ctx, login, loginCredential)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 contracts.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (contracts.LoginResult, error)); ok {
		return rf(ctx, login, loginCredential)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) contracts.LoginResult); ok {
		r0 = rf(ctx, login, loginCredential)
	} else {
		r0 = ret.Get(0).(contracts.LoginResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, login, loginCredential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockServerClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - loginCredential []byte
func (_e *MockServerClient_Expecter) Login(ctx interface{}, login interface{}, loginCredential interface{}) *MockServerClient_Login_Call {
	return &MockServerClient_Login_Call{Call: _e.mock.On("Login", ctx, login, loginCredential)}
}

func (_c *MockServerClient_Login_Call) Run(run func(ctx context.Context, login string, loginCredential []byte)) *MockServerClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockServerClient_Login_Call) Return(_a0 contracts.LoginResult, _a1 error) *MockServerClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_Login_Call) RunAndReturn(run func(context.Context, string, []byte) (contracts.LoginResult, error)) *MockServerClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockServerClient) RefreshToken(ctx context.Context, refreshToken string) (contracts.LoginResult, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 contracts.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (contracts.LoginResult, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) contracts.LoginResult); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(contracts.LoginResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockServerClient_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockServerClient_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockServerClient_RefreshToken_Call {
	return &MockServerClient_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockServerClient_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockServerClient_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerClient_RefreshToken_Call) Return(_a0 contracts.LoginResult, _a1 error) *MockServerClient_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (contracts.LoginResult, error)) *MockServerClient_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, login, loginCredential
func (_m *MockServerClient) Register(ctx context.Context, login string, loginCredential []byte) (contracts.Tokens, error) {
	ret := _m.Called(ctx, login, loginCredential)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 contracts.Tokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (contracts.Tokens, error)); ok {
		return rf(ctx, login, loginCredential)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) contracts.Tokens); ok {
		r0 = rf(ctx, login, loginCredential)
	} else {
		r0 = ret.Get(0).(contracts.Tokens)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, login, loginCredential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockServerClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - loginCredential []byte
func (_e *MockServerClient_Expecter) Register(ctx interface{}, login interface{}, loginCredential interface{}) *MockServerClient_Register_Call {
	return &MockServerClient_Register_Call{Call: _e.mock.On("Register", ctx, login, loginCredential)}
}

func (_c *MockServerClient_Register_Call) Run(run func(ctx context.Context, login string, loginCredential []byte)) *MockServerClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockServerClient_Register_Call) Return(_a0 contracts.Tokens, _a1 error) *MockServerClient_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerClient_Register_Call) RunAndReturn(run func(context.Context, string, []byte) (contracts.Tokens, error)) *MockServerClient_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SetupEncryption provides a mock function with given fields: ctx, accessToken, encKDFSalt, encKDFParams
func (_m *MockServerClient) SetupEncryption(ctx context.Context, accessToken string, encKDFSalt []byte, encKDFParams []byte) error {
	ret := _m.Called(ctx, accessToken, encKDFSalt, encKDFParams)

	if len(ret) == 0 {
		panic("no return value specified for SetupEncryption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, []byte) error); ok {
		r0 = rf(ctx, accessToken, encKDFSalt, encKDFParams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerClient_SetupEncryption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupEncryption'
type MockServerClient_SetupEncryption_Call struct {
	*mock.Call
}

// SetupEncryption is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - encKDFSalt []byte
//   - encKDFParams []byte
func (_e *MockServerClient_Expecter) SetupEncryption(ctx interface{}, accessToken interface{}, encKDFSalt interface{}, encKDFParams interface{}) *MockServerClient_SetupEncryption_Call {
	return &MockServerClient_SetupEncryption_Call{Call: _e.mock.On("SetupEncryption", ctx, accessToken, encKDFSalt, encKDFParams)}
}

func (_c *MockServerClient_SetupEncryption_Call) Run(run func(ctx context.Context, accessToken string, encKDFSalt []byte, encKDFParams []byte)) *MockServerClient_SetupEncryption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].([]byte))
	})
	return _c
}

func (_c *MockServerClient_SetupEncryption_Call) Return(_a0 error) *MockServerClient_SetupEncryption_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerClient_SetupEncryption_Call) RunAndReturn(run func(context.Context, string, []byte, []byte) error) *MockServerClient_SetupEncryption_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerClient creates a new instance of MockServerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerClient {
	mock := &MockServerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
