// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	contracts "github.com/aikowocki/yandex-go-final-diploma/internal/client/contracts"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenStore is an autogenerated mock type for the TokenStore type
type MockTokenStore struct {
	mock.Mock
}

type MockTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenStore) EXPECT() *MockTokenStore_Expecter {
	return &MockTokenStore_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function with no fields
func (_m *MockTokenStore) Clear() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockTokenStore_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockTokenStore_Expecter) Clear() *MockTokenStore_Clear_Call {
	return &MockTokenStore_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockTokenStore_Clear_Call) Run(run func()) *MockTokenStore_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenStore_Clear_Call) Return(_a0 error) *MockTokenStore_Clear_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_Clear_Call) RunAndReturn(run func() error) *MockTokenStore_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with no fields
func (_m *MockTokenStore) Load() (contracts.Tokens, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 contracts.Tokens
	var r1 error
	if rf, ok := ret.Get(0).(func() (contracts.Tokens, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() contracts.Tokens); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(contracts.Tokens)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockTokenStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockTokenStore_Expecter) Load() *MockTokenStore_Load_Call {
	return &MockTokenStore_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockTokenStore_Load_Call) Run(run func()) *MockTokenStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenStore_Load_Call) Return(_a0 contracts.Tokens, _a1 error) *MockTokenStore_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenStore_Load_Call) RunAndReturn(run func() (contracts.Tokens, error)) *MockTokenStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: t
func (_m *MockTokenStore) Save(t contracts.Tokens) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(contracts.Tokens) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTokenStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - t contracts.Tokens
func (_e *MockTokenStore_Expecter) Save(t interface{}) *MockTokenStore_Save_Call {
	return &MockTokenStore_Save_Call{Call: _e.mock.On("Save", t)}
}

func (_c *MockTokenStore_Save_Call) Run(run func(t contracts.Tokens)) *MockTokenStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(contracts.Tokens))
	})
	return _c
}

func (_c *MockTokenStore_Save_Call) Return(_a0 error) *MockTokenStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_Save_Call) RunAndReturn(run func(contracts.Tokens) error) *MockTokenStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenStore creates a new instance of MockTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenStore {
	mock := &MockTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
